// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdwbkfptevufwyozpfjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkd2JrZnB0ZXZ1Znd5b3pwZmpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjEyMzUsImV4cCI6MjA2OTQ5NzIzNX0.zT8FQmZWkEysNuhwht3e_0VMY6V3t7kBkJ6mvVw_-sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});